### ISSUE TITLE
Can't get updates from server

### ISSUE THREAD

**Issue by mgscreativa** [xavia-io/xavia-ota#6]
Hi! followed the docker setup instructions and set up my app to use expo-updates package. Created a development build in Android and created a production build. When my app tries to run `Updates.checkForUpdateAsync()` gets an error as follows:

**{ [Error: Failed to parse manifest data: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject] code: 'ERR_UPDATES_CHECK' }**

I can access the server to the published URL and I can publish updates with the `build-and-publish-app-release.sh` script. I also can see the updates listed but can't update from my app.

## Relevant app config

```
    updates: {
      checkAutomatically: 'NEVER',
      url: 'https://updates.xxxx.com',
      codeSigningCertificate: './../../../../../XXXX/XXXX/Data/XXXX/empresa/data/XXXX/expo-update-keys/app-XXXX/certs/certificate.pem',
      codeSigningMetadata: {
        keyid: 'main',
        alg: 'rsa-v1_5-sha256',
      },
    },
```

## setupUpdates app hook
Set up the app update code in a React hook

```
import { useEffect } from 'react';
// import { Platform } from 'react-native';
import * as Updates from 'expo-updates';

import config from '../config';
import { appState } from '../stores';

export default async function setupUpdates() {
  const { setIsStartupUpdateCheckComplete, addSystemLog } = appState(
    ({ setIsStartupUpdateCheckComplete, addSystemLog }) => ({
      setIsStartupUpdateCheckComplete,
      addSystemLog,
    }),
  );

  useEffect(() => {
    checkForUpdateAsync()
      .then(() => null)
      .catch(() => null);
  }, []);

  const checkForUpdateAsync = async () => {
    addSystemLog(`[Expo Updates] Checking for available updates`);

    await doExpoUpdatesSync();
  };

  const doExpoUpdatesSync = async () => {
    // if (Platform.OS === 'web' || __DEV__) {
    //   addSystemLog('[Expo Updates] Dev mode, not updating');
    //   setIsStartupUpdateCheckComplete(true);
    //
    //   return false;
    // }

    addSystemLog(`[Expo Updates] Executing sync`);
    try {
      const update = await Updates.checkForUpdateAsync();

      if (!update.isAvailable) {
        addSystemLog(`[Expo Updates] The app is up-to-date with the Expo Updates server`);
      }

      // addSystemLog(`[Expo Updates] Fetching the update`);
      // const result = await Updates.fetchUpdateAsync();

      // if (result.isNew) {
      //   addSystemLog(`[Expo Updates] Update has been installed, reloading`);
      //
      //   await Updates.reloadAsync();
      // }

      setIsStartupUpdateCheckComplete(true);
    } catch (e) {
      setIsStartupUpdateCheckComplete(true);

      console.error(e);
      throw e;
    }
  };
}
```

## Main App hook execution

```
...
...
import {
...
...
  setupNotifications,
...
...
} from './app/hooks';

...
...

function mainApp() {
...
...
  setupUpdates();
...
...
```

Docker compose file (put the server behind a proxy)

```
services:
  xavia_ota:
    image: xaviaio/xavia-ota:1.0.2
    restart: always
    container_name: xavia-ota
    volumes:
      - /media/data/xavia-ota/local-releases:/app/local-releases
    environment:
      - HOST=https://updates.xxxx.com
      - BLOB_STORAGE_TYPE=local
      - DB_TYPE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=XXXXXX
      - POSTGRES_DB=releases_db
      - POSTGRES_HOST=xavia_postgres
      - POSTGRES_PORT=5432
      - PRIVATE_KEY_BASE_64=XXXXXXX
      - ADMIN_PASSWORD=XXXXXXXX
    ports:
      - '43000:3000'
    depends_on:
      - xavia_postgres

  xavia_postgres:
    image: postgres:14
    restart: always
    container_name: xavia-postgres
    volumes:
      - /media/data/xavia-ota/postgres/postgres_data:/var/lib/postgresql/data
      - /media/data/xavia-ota/postgres/schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XXXXXX
      POSTGRES_DB: releases_db
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
```
